### ISSUE TITLE
zigzag tooltip pushes artwork sidebar off to side

### ISSUE THREAD

**Issue by joeyAghion** [artsy/force#919] opened 2017-02-21 01:50 UTC
I observed this [here](https://www.artsy.net/artwork/keith-haring-man-stretching-radiant-baby) in a fresh incognito window. Looks like:

![](https://cl.ly/0X3F0M2w2Q2B/Screen%20Shot%202017-02-20%20at%208.47.10%20PM.png)

**Comment by alloy** [comment] 2017-02-21 11:57
Duplicate of #831. If you have information on how to reproduce this, please add them there.

**Closed by alloy** 2017-02-21 11:57 UTC
Labels: bug
