### ISSUE TITLE
Content below works sometimes doesn't load on overview page

### ISSUE THREAD

**Issue by broskoski** [artsy/force#21] opened 2016-08-16 19:49 UTC
_From @briansw on July 29, 2016 14:9_

Happens pretty consistently for this artist: https://www.artsy.net/artist/jonathan-horowitz. Most of the time there's no JS error and other times I get this:

![screen shot 2016-07-29 at 10 10 47 am](https://cloud.githubusercontent.com/assets/1022172/17250920/74acceea-5574-11e6-848f-c6bcc2ad1dfb.png)

Browser height: 905
Browser width: 1452

_Copied from original issue: artsy/force-private#5428_

**Comment by broskoski** [comment] 2016-08-16 19:49
_From @mzikherman on July 29, 2016 19:3_

https://github.com/artsy/force/pull/5430/files fies the JS error, but it doesn't fix the intermittent not showing of the content below the works section.

**Comment by alloy** [comment] 2016-12-06 21:01
@briansw I’m closing this, as I’m unable to reproduce it at this moment. Please re-open if you can.

**Closed by alloy** 2016-12-06 21:01 UTC
Labels: bug, GMV
