### ISSUE TITLE
Purchase request QA 2.0

### ISSUE THREAD

**Issue by anipetrov** [artsy/force#580] opened 2016-12-16 19:49 UTC
- [ ] A few times, I was not able to purchase request with a new user. I cannot reliably reproduce.

![screen recording 2016-12-15 at 17 29](https://cloud.githubusercontent.com/assets/8701687/21244787/32cce6e0-c2ed-11e6-8bf8-040ed230e62a.gif)

- [ ] Do not see the error event `Purchase request failed to submit` firing. i.e. every time the “send request” button is clicked and it fails, we need to report the reason for the failure.

Everything else seem to be firing perfectly!
Reference issue: https://github.com/artsy/force/issues/463

cc @1aurabrown @alloy

**Comment by alloy** [comment] 2016-12-16 20:00
I see the errors count increasing in your console, but your console says they are “hidden by filters”. Do you still have the console open and can you reveal the errors?

It also seems like maybe the purchase button doesn’t gracefully handle recovering after an error has occurred.

**Comment by anipetrov** [comment] 2016-12-16 20:02
Oh yeah, forgot to mention -- it was the same 404 error Brian had mentioned earlier:
```
jquery.js:8630 GET https://stagingapi.artsy.net/api/v1/user?email=ani%40artsymail.testtesttesttest&session_id=ae08bb40-4e8a-11e6-a101-03f868ee9047 404 (Not Found)
```

**Comment by alloy** [comment] 2016-12-16 20:03
Do you know where I can find more detail about that? /cc @briansw

**Comment by briansw** [comment] 2016-12-16 20:06
@alloy this was the issue I made for the 404 I was getting: https://github.com/artsy/force/issues/532

**Comment by alloy** [comment] 2016-12-16 22:13
Hmm, that’s supposedly fixed by #535, although I’m not sure what part of that PR is supposed to fix it. @1aurabrown can you share your thoughts on this?

**Comment by 1aurabrown** [comment] 2016-12-19 14:08
@anipetrov in the imge you included, it looks like the signup probably failed, not the purchase. you would have seen an analytics message for successful signup before you would see a purchase success or failure event. I'm not able to reproduce this, but it's hard to see what was going on in your case because the only messages being shown are analytics info logs. If this happens again can you take a screenshot of the messages in the ALL tab and untick the box for hiding network messages?

**Comment by 1aurabrown** [comment] 2016-12-19 14:13
fwiw, in a true failure of the _inquiry_ POST, the analytics event does fire. Here is an example with a reliable way to produce a failure, inquiring as an admin:

![screen shot 2016-12-19 at 3 09 45 pm](https://cloud.githubusercontent.com/assets/3171662/21315612/4c8889be-c5fd-11e6-928a-b88e0a8164e8.png)
![screen shot 2016-12-19 at 3 09 51 pm](https://cloud.githubusercontent.com/assets/3171662/21315613/4c9855b0-c5fd-11e6-8404-d2fbe44ae1be.png)
![screen shot 2016-12-19 at 3 09 21 pm](https://cloud.githubusercontent.com/assets/3171662/21315611/4c83ddba-c5fd-11e6-87d0-9e601a880eb7.png)

However, I did come across a different bug where when you try to sign up with an email address already associated with an account, an error would prevent the modal from being invoked. will pr a fix.

**Comment by 1aurabrown** [comment] 2016-12-19 16:08
Other information for context: a 404 at `https://stagingapi.artsy.net/api/v1/user?email=ani%40artsymail.testtesttesttest&session_id=ae08bb40-4e8a-11e6-a101-03f868ee9047 404 (Not Found)` should not cause a failure for a user to be created or for an inquiry to be submitted. This failure is expected in the case that the email address entered in the sign up form does not match an existing account. The 404 means that no such account exists. If the user creation and/or inquiry submission is also failing, then this points to a problem either in the way that request to check for an account is handled, or the handling of some other logic afterwards.

**Comment by mzikherman** [comment] 2016-12-19 18:13
Looks great! I wasn't able to reproduce the new user issue either on staging. Signing up and existing user flows seem good to me 👍 

One tiny thought, maybe we could pre-fill the already entered email on this screen?

<img width="492" alt="screen shot 2016-12-19 at 1 07 32 pm" src="https://cloud.githubusercontent.com/assets/1457859/21323746/ec3f9404-c5ec-11e6-8da5-b7495df9cb57.png">

**Comment by alloy** [comment] 2016-12-19 19:02
I agree with @mzikherman and would _also_ say the same for the password. Ideally we could just sign-them in instead of showing a modal at all?

**Comment by 1aurabrown** [comment] 2016-12-20 15:07
@alloy assuming the password they used in trying to create a new account is the same as the one on the existing account. not sure if that is worth tackling for the purpose of the test? @briansw ?

**Comment by briansw** [comment] 2016-12-20 15:36
Agree, doesn't seem worth addressing for the test, but it's a great idea and we should do this across the site in the future!

**Comment by alloy** [comment] 2016-12-20 16:25
Yup, agreed on not doing it for the test. I'll file a new ticket for it.

Regarding the origins ticket, we have a separate ticket for the mysterious error and it seems like the event that @anipetrov is asking for actually does fire. Is that correct @1aurabrown and this can we close this?

**Comment by 1aurabrown** [comment] 2016-12-20 17:43
@alloy there is another ticket that brain opened, but i had also closed it. i suppose we can close these until they surface again?

**Comment by anipetrov** [comment] 2016-12-20 18:16
Sorry, my intention was that the error event is fired every time the `send request` button is pressed but the request does not go through. We could gather the errors (though i am not sure any error messages display, just fields light up in red) in a hash `errors` property.

**Comment by alloy** [comment] 2016-12-20 18:50
@anipetrov Thanks, I updated your original description.

**Comment by 1aurabrown** [comment] 2016-12-21 18:47
I'm going to close this issue as there is a different one for the error brian was getting, and there is also a new issue in the ice box about pre-filling user signing fields.

**Closed by 1aurabrown** 2016-12-21 18:47 UTC
