### ISSUE TITLE
[Artist Banner CTA] Related artists should be filtered if they are already present in the list

### ISSUE THREAD

**Issue by broskoski** [artsy/force#752] opened 2017-01-24 19:56 UTC
https://www.dropbox.com/s/i6d74e1ld245uj0/Screenshot%202017-01-24%2014.54.20.png?dl=0

**Comment by alloy** [comment] 2017-01-24 20:44
Closing as a dupe of #756.

**Closed by alloy** 2017-01-24 20:44 UTC
Labels: QA
