### ISSUE TITLE
Lightbox zoom feature acts a little strange with scroll wheels

### ISSUE THREAD

**Issue by briansw** [artsy/force#462] opened 2016-12-06 14:13 UTC
When trying to zoom in it zooms out and when it does zoom in, it only moves a small amount.
https://cl.ly/3t3z3k0L3R2c

**Comment by alloy** [comment] 2017-01-05 15:38
@briansw Could you elaborate a bit on this / fix the link?

**Comment by briansw** [comment] 2017-01-05 15:44
@alloy woops, link updated. That's me trying to zoom in the entire time.

**Comment by alloy** [comment] 2017-01-05 17:44
Thanks 👍

**Comment by mzikherman** [comment] 2017-01-10 20:54
Hmm, looks fine to me? Is it that you're using a mouse w/ scroll wheel, or a weird browser?

Doing the 'two finger scroll' on my apple mouse and Chrome looks fine to me.

**Comment by briansw** [comment] 2017-01-10 20:56
Yes, it's a scroll wheel mouse.

**Comment by xtina-starr** [comment] 2017-01-31 19:05
@briansw I tried to reproduce this issue with the scroll wheel on a couple different works in production and locally. It seems to work fine for me, but perhaps we can sit down together to try to reproduce this.

**Comment by xtina-starr** [comment] 2017-01-31 19:39
This seems to be an odd one off that we weren't able to reproduce on my machine using both chrome and safari. I'm going to go ahead and close it.

**Closed by xtina-starr** 2017-01-31 19:39 UTC
Labels: bug, Collector Experience

**Comment by alloy** [comment] 2017-01-31 20:26
Did you try it on your machine with Brain's mouse?

**Comment by briansw** [comment] 2017-01-31 20:28
Yeah, it seems like it's unique to my machine...
