### ISSUE TITLE
QA: Marketing landing page

### ISSUE THREAD

**Issue by briansw** [artsy/force#1020] opened 2017-03-16 18:38 UTC
This looks great! It's very close, mostly just a few simple cosmetic issues to take care of:

### Landing page
- [x] Signup buttons don't work yet
- [x] Update footer bg img: https://cl.ly/2k1p2L1K3X3d
- [x] Remove `font-weight: bold` from all avant garde text
- [x] icons in the "used by the most experienced collectors" module should be centered at mobile breakpoint
- [x] News publications should be centered at all breakpoints
- [x] Getting a horizontal scrollbar at any browser width less than 1375px
- [x] Change page URL to `/collect-art`
- [x] Make padding `20px` on right side of FB signup buttons
- [x] Email icon needs to go up a pixel or two to center vertically on text
- [x] All the world's art in one place apostrophe should be `&rsquo;`
- [x] Hover states: purple buttons turn black with white type, FB buttons turn purple, Sign up with email turn purple with white type/icon
- [x] Typo: Consule should be Consult

### Signup page
- [x] Don't display auction popups
- [x] Put focus on the first field on load
- [x] height of artsy logo should be 40px
- [x] header font size should be `garamond-l-headline` at desktop and `garamond-headline` at mobile
- [x] Fields order: Name, email, password 

### Unrelated, but still a blocker
Need to make sure personalization is working properly before handing over to flatiron

**Comment by briansw** [comment] 2017-03-16 18:39
@wrgoldstein when you have a second can you give this a look for analytics requirements?

**Comment by mzikherman** [comment] 2017-03-16 18:43
I checked off 3 of these so far, they look to have been addressed by this PR that was just merged (https://github.com/artsy/force/pull/1018)

**Comment by wrgoldstein** [comment] 2017-03-16 19:42
Following https://github.com/artsy/minotaur/blob/master/doc/instrumentation/analytics_mlp_checklist.md:

The KPI is obviously accounts created-- is there an established conversion to sign up rate from other landing pages of similar intent?

Instrumentation to add:

- instrumenting all of the clicks of sign up buttons
- instrumenting the actual signup itself

```js
// click instrumentation example
analytics.track('click', { 
  type: 'form interaction',
  label: 'Sign up using your email address',
  flow: 'auth',
  destination_path: null,
  context: 'hero1: an art collection for every budget'
})
```


It looks to me like there's no click tracking yet, and the links don't resolve anywhere yet.  Let me know when that's all in place and I can check it's all there.

**Comment by yuki24** [comment] 2017-03-17 14:10
The issues for the landing page has been fixed and it should be ready for review. I'm still working on the signup page and will let you know as soon as we merge it.

**Comment by anipetrov** [comment] 2017-03-21 15:01
We see only header buttons sending events, and there the properties seem a little off. This is a more detailed list of what we'd want to see, let me know if it makes sense!

## Header buttons: 
![image](https://cloud.githubusercontent.com/assets/8701687/24152345/bf9f6582-0e21-11e7-836f-fde10b002913.png)
- [ ] **Click**: fires when the header sign up using email button is clicked 
  - properties: { 
type: 'button',
label: 'Sign up using email',
destination_path: null,
context_module: 'header: an art collection for every budget'
}

- [ ] **Click**: fires when the header sign up with facebook button is clicked 
  - properties: { 
type: 'button',
label: 'Sign up with facebook',
destination_path: null,
context_module: 'header: an art collection for every budget'
}

## _All the world's art in one place_ button: 
![image](https://cloud.githubusercontent.com/assets/8701687/24153405/ba9860a4-0e24-11e7-979e-ff7df3a7bf80.png)
- [ ] **Click**: fires when the sign up button in the _All the world's art in one place_ section is clicked
  - properties: { 
type: 'button',
label: 'Sign up',
destination_path: null,
context_module: 'all the world's art in one place'
}

## _Used by the most experienced collectors_ button: 
![image](https://cloud.githubusercontent.com/assets/8701687/24153465/ecab3f9e-0e24-11e7-8679-b38932073fc5.png)
- [ ] **Click**: fires when the sign up button in the _Used by the most experienced collectors_ section is clicked
  - properties: { 
type: 'button',
label: 'Sign up',
destination_path: null,
context_module: 'used by the most experienced collectors'
}

## FAQ button: 
![image](https://cloud.githubusercontent.com/assets/8701687/24153498/10f73902-0e25-11e7-8a83-fb7b83684a8f.png)
- [ ] **Click**: fires when the sign up button in the _Used by the most experienced collectors_ section is clicked
  - properties: { 
type: 'button',
label: 'Sign up',
destination_path: null,
context_module: 'faq'
}

## Footer buttons: 
![image](https://cloud.githubusercontent.com/assets/8701687/24153634/69ff9008-0e25-11e7-816d-ef4beda78084.png)

- [ ] **Click**: fires when the header sign up using email button is clicked 
  - properties: { 
type: 'button',
label: 'Sign up using email',
destination_path: null,
context_module: 'footer: start buying art by your favorite artists on artsy'
}

- [ ] **Click**: fires when the header sign up with facebook button is clicked 
  - properties: { 
type: 'button',
label: 'Sign up with facebook',
destination_path: null,
context_module: 'footer: start buying art by your favorite artists on artsy'
}

**Comment by briansw** [comment] 2017-03-21 15:30
@xtina-starr @yuki24 it looks like the icons from the "Used by the most experienced collectors" aren't loading.

**Comment by xtina-starr** [comment] 2017-03-21 15:38
@yuki24 how about you look into what's going on with the icons and I'll take on the analytics stuff. Or I can take both. I'm not sure of your availability today.

**Comment by yuki24** [comment] 2017-03-21 15:41
@xtina-starr I'll take the icons 👍

**Comment by yuki24** [comment] 2017-03-21 15:50
@briansw It seems like the issue is present only in staging, but I'll fix it now.

**Comment by xtina-starr** [comment] 2017-03-21 15:51
@anipetrov quick question. I'm seeing that destination_path should be `null` even though this button takes the user to the sign up page. Is that intentional?

**Comment by anipetrov** [comment] 2017-03-21 15:53
ah yeah, it's not a modal firing but a standalone page -- we can add the destination path!

**Comment by xtina-starr** [comment] 2017-03-21 16:07
@anipetrov will do!

**Closed** 2017-03-24 19:11 UTC
Labels: QA
